### ISSUE TITLE
Creating DO k8s cluster with two masters

### ISSUE THREAD

**Issue by bjg2** [chukaofili/kubernetes-on-digitalocean#1]
Hi Chuka,

First, thanks for this tutorial. I follow it and it really helps. And sorry for opening issue - this is not an issue, I just didn't know how to communicate differently.

I'm imitating your initial 'kubernetes on digitalocean' setup, only i would like to make a different nodes configuration. I would like to create 3 environments in DO, test with 1 node, stage with 1 node, and prod with 2 nodes + load balancer (more is not needed for now, just want to add some HA to the current setup and to make sure i could easily scale in future). Thing is, in this setup I would like all my nodes to be both masters and to host pods.

So, for example, I would like to build a cluster to:
* Have two nodes that are both masters and both can host pods
* Have one LB
* Cluster works when any of nodes is down (single node)
* Local kubectl works when any of nodes is down (single node)

I was trying to create such a setup by imitating your step for creating master, then imitating your step for creating one worker, and then doing `kubectl --kubeconfig=${CLUSTER_KUBECTL_CONFIG} patch node ${WORKER_NODE} -p '{"metadata":{"labels":{"node-role.kubernetes.io/master":""}},"spec":{"taints":[{"effect":"NoSchedule","key":"node-role.kubernetes.io/master","timeAdded":null}]}}` and `kubectl --kubeconfig=${CLUSTER_KUBECTL_CONFIG} --all node-role.kubernetes.io/master-`. It seems that this setup doesn't actually helps - `kubectl --kubeconfig=${CLUSTER_KUBECTL_CONFIG} get nodes` says that I have two masters, when I put second master (the one created as worker) down everything still works (local kubectl and cluster is up), but when I put initial master (the one created as master) down I cannot connect to the cluster anymore via kubectl. Changing IP in kubectl config to second node doesn't help. Error is `The connection to the server 159.89.27.117:6443 was refused - did you specify the right host or port?`.

So I guess my setup for second master is flaky and that I should run some other commands, but googling didn't help. It would be super-nice if you would know what I'm doing wrong and help me with advice.

Thanks, Aleksandar

**Comment by bjg2** [comment]
Found asnwers @ https://blog.inkubate.io/install-and-configure-a-multi-master-kubernetes-cluster-with-kubeadm/, thanks anyway!

**Comment by chukaofili** [comment]
@bjg2 That't great, closing.
