### ISSUE TITLE
Help Wanted

### ISSUE THREAD

**Issue by matthewoestreich** [chukaofili/kubernetes-on-digitalocean#3]
I am not sure if you can assist here, but I'm getting desperate! I have followed your guide and it works flawlessly - the only issue is when I try to connect to the cluster through the load balancer, I always get 503 Service Unavailable - even though the Load Balancer in Digital Ocean is showing as Healthy.... I am stumped....

**Comment by chukaofili** [comment]
Hi @oze4 , Did you confirm the pods are up and running? Usually a 503 Service Unavailable indicates the pods are not reachable from the service.

**Comment by matthewoestreich** [comment]
Thank you so much for your response, @chukaofili ! 

To elaborate, yes, the pods are available on their public IP's - this piece works just fine.. It may be worth mentioning I only have a single worker node with one master node.

Please see the URLs below, but direct to droplet works just fine.. Yet, if you try via the load balancer, it does not work. As a test, I also opened port 30580 on the load balancer and forward requests to the pod over that same port (30580) - this works just fine, which is very odd.. It's almost like the load balancer doesn't forward 80 to 30580, but it "passes" 30580 through just fine.

- Direct to droplet:  http://68.183.50.188:30630/ -or- http://68.183.50.188:30630/healthz 
- Load Balancer: http://159.89.253.116
- Load Balancer (using forwarded node port): http://159.89.253.116:30630 -or- http://159.89.253.116:30630/healthz

The really odd thing is that the Load Balancer shows healthy....
![image](https://user-images.githubusercontent.com/21092343/67289414-33a86a80-f4a4-11e9-8ec4-47fcf08ac33d.png)

These are the forwarding rules:
![image](https://user-images.githubusercontent.com/21092343/67303096-8ccdc980-f4b7-11e9-927c-4ea54331e757.png)

These are the manifests that I used (I had to modify them, as the ones listed in the how-to no longer exist in those locations): https://github.com/oze4/k8-digital-ocean-nginx-ingress-controller

Which is odd because I can even see the load blancer IP within the ingress controller logs:
![image](https://user-images.githubusercontent.com/21092343/67286192-91d24f00-f49e-11e9-9b9b-c31bd86531ad.png)


Thank you so much for responding!! Any help would be GREATLY appreciated!

**Comment by chukaofili** [comment]
hey @oze4 Sorry i haven't responded sooner. Currently traveling. Are you still having issues? Can you send a copy of your deployment files? including the service files.

**Comment by matthewoestreich** [comment]
@chukaofili no worries! I wound up just purchasing Digital Oceans official Kubernetes offering (same price per node as regular droplets).. This has been working like a charm.. One day I will figure out a "bare-metal" deployment!

Thank you VERY much for your responses!!

Enjoy your travels, and be safe 😄
